 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `repo`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=172.20.0.213;Database=SanalPos;User Id=prd_sanalpos;password=**zapped**;Application Name='SANALPOS'`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`


 // <auto-generated />
using System;
using System.Collections.Generic;
using System.Configuration; 
using System.Data.Common;
using System.Data;
namespace LorePdks.COMMON.Enums
{
    public class siltireileberaber_AppEnums
    {
		
public enum Odeme_Yontem 
		{   
			Empty = 0, 
		   	Kredi_Karti = 1010001,
			Google_pay = 1010002,
			HavaleEft = 1010003,
			BKM_ekspress = 1010004,
			Amerikan_Ekspress = 1010005
		}
		public enum Odeme_Yontem_Guvenlik 
		{   
			Empty = 0, 
		   	_2D_guvenlik = 1020001,
			_3D_guvenlik = 1020002
		}
		public enum Odeme_Durum 
		{   
			Empty = 0, 
		   	Key_Olusturuldu = 1030001,
			Odeme_Icin_Bekleniyor = 1030002,
			Istek_Tahsilat_Icin_Bankaya_Gonderildi = 1030003,
			Odeme_Basarili = 1030004,
			Odeme_Basarisiz = 1030005,
			Odeme_Key_Suresi_Doldu = 1030006,
			Istek_3d_Dogrulamaya_Gonderildi = 1030007
		}
		public enum Araci_Kurum 
		{   
			Empty = 0, 
		   	Halk_Bank = 1040001,
			Ziraat_Bank = 1040002
		}
		public enum Iade_Iptal_Islem_Tip 
		{   
			Empty = 0, 
		   	Iptal = 1050001,
			Iade = 1050002
		}
		public enum Iade_Iptal_Durum 
		{   
			Empty = 0, 
		   	Basarili = 1090001,
			Basarisiz = 1090002
		}
		public enum Para_Birimi 
		{   
			Empty = 0, 
		   	Turk_Lirasi = 1100001,
			Dolar = 1100002,
			Euro = 1100003,
			Paund = 1100004
		}
		public enum Odeme_Key_Uretim_Tur 
		{   
			Empty = 0, 
		   	Api = 1110001,
			Kullanici_Istegi = 1110002
		}
		
		public enum KodTipList
		{    
			Odeme_Yontem = 101,		
					Odeme_Yontem_Guvenlik = 102,		
					Odeme_Durum = 103,		
					Araci_Kurum = 104,		
					Iade_Iptal_Islem_Tip = 105,		
					Iade_Iptal_Durum = 109,		
					Para_Birimi = 110,		
					Odeme_Key_Uretim_Tur = 111		
		




} 
	}
}