



// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Connection`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=94.73.147.166;Port=3306;Database=u1555990_lorepdk;User ID=u1555990_updks;password=**zapped**;`
//     Schema:                 `u1555990_lorepdk`
//     Include Views:          `True`

//     Factory Name:          `MySqlClientFactory`
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_deneme
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_deneme
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >>  return result  : Microsoft.VisualStudio.TextTemplating6CEDEC15A2146D3B72870079B8130198090638F144E6D5B3E91EE428C3275DE81BEF4A1BA74B4F2DCF18887C09F920AE1A9FAC8CE1E251CF757DF65166AE15D0.GeneratedTextTransformation+Tables
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Connection`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=94.73.147.166;Port=3306;Database=u1555990_lorepdk;User ID=u1555990_updks;password=**zapped**;`
//     Schema:                 `u1555990_lorepdk`
//     Include Views:          `True`

//     Factory Name:          `MySqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.



// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace LorePdks.DAL.Models
{
}
#pragma warning restore 1591

