



// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Connection`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=94.73.147.166;Port=3306;Database=u1555990_lorepdk;User ID=u1555990_updks;password=**zapped**;`
//     Schema:                 `u1555990_lorepdk`
//     Include Views:          `True`

//     Factory Name:          `MySqlClientFactory`
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_firma
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_firma
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : AD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : KOD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ACIKLAMA
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ADRES
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CIHAZ_TIP_KID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MESAI_SAAT
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MOLA_SAAT
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CUMARTESI_MESAI_SAAT
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CUMARTESI_MOLA_SAAT
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_firma_cihaz
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_firma_cihaz
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CIHAZ_MAKINE_GERCEK_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_CIHAZ_TIP_KID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : AD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ACIKLAMA
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_firma_kisi
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_firma_kisi
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : KISI_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_KISI_TIP_KID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_hareket
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_hareket
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : HAREKET_TIP_KID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : HAREKET_DURUM_KID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : HAREKET_KAYIT_TARIH
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : HAREKET_DATA
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : HAREKET_ISLEME_TARIH
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_kisi
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_kisi
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : AD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : SOYAD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : TC
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CEP_TEL
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : EMAIL
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_kod
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_kod
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : TIP_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : KOD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : SIRA
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : KISA_AD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : DIGER_UYG_ENUM_AD
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : DIGER_UYG_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_login_user
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_login_user
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : USER_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : USER_NAME
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : TOKEN
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : IP_ADRESI
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : USER_AGENT
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : EXP_DATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_pdk
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_pdks
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : KISI_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : FIRMA_CIHAZ_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : GIRIS_TARIH
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CIKIS_TARIH
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_pdks_hareket
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_pdks_hareket
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : PDKS_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : HAREKET_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >> !makeSingular >>  t.ClassName : t_user
//   foreach (var t in result) >> t.ClassName = ClassPrefix + t.ClassName + ClassSuffix;  : t_user
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : KISI_ID
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : USER_NAME
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : SIFRE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : AKTIF
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : ISDELETED
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : CREATEDDATE
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDUSER
//   foreach (var t in result) >> foreach (var c in t.Columns) >>  c.PropertyName;  : MODIFIEDDATE
//   foreach (var t in result) >>  return result  : Microsoft.VisualStudio.TextTemplatingB80B5E5B29EBDD85CB56281A54B2CF82FF3E712209A392A6722C7F119824052AAAED73B168C1CF1ECAC742AC6CF3FC598B8988CF301B3D04C42DA46F07787A29.GeneratedTextTransformation+Tables
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Connection`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=94.73.147.166;Port=3306;Database=u1555990_lorepdk;User ID=u1555990_updks;password=**zapped**;`
//     Schema:                 `u1555990_lorepdk`
//     Include Views:          `True`

//     Factory Name:          `MySqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.



// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LorePdks.DAL.Model;
namespace LorePdks.DAL.Model
{
}
#pragma warning restore 1591

