// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.



// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LorePdks.DAL.Model;
namespace LorePdks.DAL.Model
{
    public partial class t_deneme  : _BaseModel
    {
		public t_deneme() 
		{
		}

        [Required]
        public int ID { get; set;}
    } 
	public enum t_deneme_PROPERTIES {

		ID,
		
	}
}
#pragma warning restore 1591
