// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.



// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LorePdks.DAL.Model;
namespace LorePdks.DAL.Model
{
    public partial class t_firma_kisi  : _BaseModel
    {
		public t_firma_kisi() 
		{
		}

     //   [AutoIncrement]
     [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]	
	  public int ID { get; set;}
        [Required]
        public int FIRMA_ID { get; set;}
        [Required]
        public int KISI_ID { get; set;}
        public int? FIRMA_KISI_TIP_KID { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public int? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public int? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string FIRMA_KISI_CIHAZ_KOD { get; set;}
    } 
	public enum t_firma_kisi_PROPERTIES {

		ID,
		FIRMA_ID,
		KISI_ID,
		FIRMA_KISI_TIP_KID,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		FIRMA_KISI_CIHAZ_KOD,
		
	}
}
#pragma warning restore 1591
