// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.



// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LorePdks.DAL.Model;
namespace LorePdks.DAL.Model
{
    public partial class t_kamera_hareket  : _BaseModel
    {
		public t_kamera_hareket() 
		{
		}

     //   [AutoIncrement]
     [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]	
	  public int ID { get; set;}
        [Required]
        public int FIRMA_ID { get; set;}
        [Required]
        public int FIRMA_CIHAZ_ID { get; set;}
        [Required]
        public DateTime OLAY_TARIHI { get; set;}
        [Required]
        public int KAMERA_OLAY_TIP_KID { get; set;}
        public string DOSYA_YOL { get; set;}
        public string ACIKLAMA { get; set;}
        public string HAM_LOG_VERISI { get; set;}
        public int? ISDELETED { get; set;}
        public int? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public int? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    } 
	public enum t_kamera_hareket_PROPERTIES {

		ID,
		FIRMA_ID,
		FIRMA_CIHAZ_ID,
		OLAY_TARIHI,
		KAMERA_OLAY_TIP_KID,
		DOSYA_YOL,
		ACIKLAMA,
		HAM_LOG_VERISI,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}
}
#pragma warning restore 1591
