// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.



// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LorePdks.DAL.Model;
namespace LorePdks.DAL.Model
{
    public partial class t_pdks_hareket  : _BaseModel
    {
		public t_pdks_hareket() 
		{
		}

     //   [AutoIncrement]
     [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]	
	  public int ID { get; set;}
        [Required]
        public int FIRMA_ID { get; set;}
        public int? KISI_ID { get; set;}
        [Required]
        public int FIRMA_CIHAZ_ID { get; set;}
        public string KULLANICI_CIHAZ_KODU { get; set;}
        [Required]
        public DateTime HAREKET_TARIHI { get; set;}
        [Required]
        public int PDKS_YON_KID { get; set;}
        public string HAM_LOG_VERISI { get; set;}
        public int? ISDELETED { get; set;}
        public int? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public int? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    } 
	public enum t_pdks_hareket_PROPERTIES {

		ID,
		FIRMA_ID,
		KISI_ID,
		FIRMA_CIHAZ_ID,
		KULLANICI_CIHAZ_KODU,
		HAREKET_TARIHI,
		PDKS_YON_KID,
		HAM_LOG_VERISI,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}
}
#pragma warning restore 1591
