// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace LorePdks.DAL.Model
{


    [Dapper.Contrib.Extensions.Table("Pos.OdemeIadeIptal")]

    public partial class T_Pos_OdemeIadeIptal    {
		public T_Pos_OdemeIadeIptal()
		{
		}

        //public static string SchemeName { get { return "Pos"; } }
        public static string GetSchema() { return "Pos"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public int ODEME_ID { get; set;}
        [Required]
        public int IADE_IPTAL_ISLEM_TIP_KID { get; set;}
        [Required]
        public int IADE_IPTAL_DURUM_KID { get; set;}
        [Required]
        public DateTime TARIH { get; set;}
        [Required]
        public decimal TUTAR { get; set;}
        public string ACIKLAMA { get; set;}
        public string ARACI_KURUM_IADE_IPTAL_REFERANS_ID { get; set;}
        [Required]
        public bool ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string CREATEDIP { get; set;}
        public string MODIFIEDIP { get; set;}
        public string SONUC_ACIKLAMA { get; set;}
    }
	
    
    public class T_Pos_OdemeIadeIptalMapper : AutoClassMapper<T_Pos_OdemeIadeIptal>
    {
        public T_Pos_OdemeIadeIptalMapper()
            : base()
        {
            Schema("Pos");
        }
    }
 
	public enum T_Pos_OdemeIadeIptal_Properties {

		ID,
		ODEME_ID,
		IADE_IPTAL_ISLEM_TIP_KID,
		IADE_IPTAL_DURUM_KID,
		TARIH,
		TUTAR,
		ACIKLAMA,
		ARACI_KURUM_IADE_IPTAL_REFERANS_ID,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		CREATEDIP,
		MODIFIEDIP,
		SONUC_ACIKLAMA,
		
	}	
}

#pragma warning restore 1591
