// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace LorePdks.DAL.Model
{


    [Dapper.Contrib.Extensions.Table("Pos.AUTH_PERMISSION")]

    public partial class T_Pos_AUTH_PERMISSION    {
		public T_Pos_AUTH_PERMISSION()
		{
		}

        //public static string SchemeName { get { return "Pos"; } }
        public static string GetSchema() { return "Pos"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        public string TYPE { get; set;}
        public string AREA { get; set;}
        public string CONTROLLER { get; set;}
        public string ACTION { get; set;}
        public string RETURN_TYPE { get; set;}
        public string NAME { get; set;}
        public string URL { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string CREATEDIP { get; set;}
        public string MODIFIEDIP { get; set;}
        [Required]
        public bool ISDELETED { get; set;}
    }
	
    
    public class T_Pos_AUTH_PERMISSIONMapper : AutoClassMapper<T_Pos_AUTH_PERMISSION>
    {
        public T_Pos_AUTH_PERMISSIONMapper()
            : base()
        {
            Schema("Pos");
        }
    }
 
	public enum T_Pos_AUTH_PERMISSION_Properties {

		ID,
		TYPE,
		AREA,
		CONTROLLER,
		ACTION,
		RETURN_TYPE,
		NAME,
		URL,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		CREATEDIP,
		MODIFIEDIP,
		ISDELETED,
		
	}	
}

#pragma warning restore 1591
