// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace LorePdks.DAL.Model
{


    [Dapper.Contrib.Extensions.Table("Pos.AUTH_USER_TOKEN")]

    public partial class T_Pos_AUTH_USER_TOKEN    {
		public T_Pos_AUTH_USER_TOKEN()
		{
		}

        //public static string SchemeName { get { return "Pos"; } }
        public static string GetSchema() { return "Pos"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        public int? USER_TOKEN_TIP_KOD_ID { get; set;}
        public string LOGIN_NAME { get; set;}
        public int? USER_ID { get; set;}
        public string AD_SOYAD { get; set;}
        public string KIMLIK_NO { get; set;}
        public string LOGIN_ARACI_UYGULAMA_TOKEN { get; set;}
        public int? LOGIN_ARACI_UYGULAMA_TIP_KID { get; set;}
        public string APP_TOKEN { get; set;}
        public string USER_AGENT { get; set;}
        public string IP { get; set;}
        public string SERVER_INFO { get; set;}
        public bool? IS_ADMIN { get; set;}
        public bool? IS_SUPER_ADMIN { get; set;}
        public int? DELETE_REASON_KOD_ID { get; set;}
        public string DELETE_REASON { get; set;}
        public DateTime? EXP_DATE { get; set;}
        public int? IS_YERINE_LOGIN { get; set;}
        public string YERINE_LOGIN_ADMIN_LOGIN_NAME { get; set;}
        public string YERINE_LOGIN_ADMIN_LOGIN_TOKEN { get; set;}
        public int? LOGIN_DTO_JSON_CLOB_ID { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string CREATEDIP { get; set;}
        public string MODIFIEDIP { get; set;}
        [Required]
        public bool ISDELETED { get; set;}
    }
	
    
    public class T_Pos_AUTH_USER_TOKENMapper : AutoClassMapper<T_Pos_AUTH_USER_TOKEN>
    {
        public T_Pos_AUTH_USER_TOKENMapper()
            : base()
        {
            Schema("Pos");
        }
    }
 
	public enum T_Pos_AUTH_USER_TOKEN_Properties {

		ID,
		USER_TOKEN_TIP_KOD_ID,
		LOGIN_NAME,
		USER_ID,
		AD_SOYAD,
		KIMLIK_NO,
		LOGIN_ARACI_UYGULAMA_TOKEN,
		LOGIN_ARACI_UYGULAMA_TIP_KID,
		APP_TOKEN,
		USER_AGENT,
		IP,
		SERVER_INFO,
		IS_ADMIN,
		IS_SUPER_ADMIN,
		DELETE_REASON_KOD_ID,
		DELETE_REASON,
		EXP_DATE,
		IS_YERINE_LOGIN,
		YERINE_LOGIN_ADMIN_LOGIN_NAME,
		YERINE_LOGIN_ADMIN_LOGIN_TOKEN,
		LOGIN_DTO_JSON_CLOB_ID,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		CREATEDIP,
		MODIFIEDIP,
		ISDELETED,
		
	}	
}

#pragma warning restore 1591
