/*
CREATE TABLE `s_sequence_table` (
  `ID` int NOT NULL AUTO_INCREMENT DEFAULT '0',
  `TABLO_ADI` nvarchar(250) COLLATE utf8_turkish_ci NOT NULL,
    `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int(20) DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int(20) DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_sequence_table_ID ON s_sequence_table (ID);

CREATE INDEX IDX_sequence_table_TABLO_ADI ON s_sequence_table (TABLO_ADI);
*/


-- CREATE TABLE `T_USER` (
  -- `ID` int NOT NULL AUTO_INCREMENT,
  -- `KISI_ID` int NOT NULL,
  -- `USER_NAME` nvarchar(500) COLLATE utf8_turkish_ci DEFAULT NULL,
  -- `SIFRE` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  -- `AKTIF` int(1) NOT NULL DEFAULT '0',
   -- `ISDELETED` int(1) NOT NULL DEFAULT 0,
  -- `CREATEDUSER` int DEFAULT NULL,
  -- `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  -- `MODIFIEDUSER` int DEFAULT NULL,
  -- `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  -- PRIMARY KEY (`ID`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

-- CREATE INDEX IDX_user_ID ON t_user (ID);

-- CREATE INDEX IDX_KISI_ID ON t_user (KISI_ID);

-- CREATE INDEX IDX_user_USER_NAME ON t_user (USER_NAME);


CREATE TABLE `T_KISI` (
  `ID` int NOT NULL AUTO_INCREMENT,
    `AD` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
	  `SOYAD` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
	    `TC` nvarchar(11) COLLATE utf8_turkish_ci DEFAULT NULL,
		  `CEP_TEL` nvarchar(20) COLLATE utf8_turkish_ci DEFAULT NULL,
		  `EMAIL` nvarchar(400) COLLATE utf8_turkish_ci DEFAULT NULL,
		  `LOGIN_NAME` nvarchar(500) COLLATE utf8_turkish_ci DEFAULT NULL,
   `SIFRE` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
   `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_KISI_ID ON T_KISI (ID);
CREATE INDEX IDX_KISI_TC ON T_KISI (TC);


CREATE TABLE `t_KISI_TOKEN` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `KISI_ID` int NOT NULL,
  `LOGIN_NAME` nvarchar(500) COLLATE utf8_turkish_ci DEFAULT NULL,
  `TOKEN` nvarchar(1000) COLLATE utf8_turkish_ci DEFAULT NULL,
  `IP_ADRESI` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  `USER_AGENT` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  `EXP_DATE` timestamp(6) NULL DEFAULT NULL,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER`int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_KISI_TOKEN_ID ON t_KISI_TOKEN (ID);
CREATE INDEX IDX_t_KISI_TOKEN_KISI_ID ON t_KISI_TOKEN (KISI_ID);
CREATE INDEX IDX_t_KISI_TOKEN_USER_NAME ON t_KISI_TOKEN (LOGIN_NAME);
CREATE INDEX IDX_t_KISI_TOKEN_TOKEN ON t_KISI_TOKEN (TOKEN);



CREATE TABLE `t_firma` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `AD` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
	`KOD` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
	    `ACIKLAMA` nvarchar(11) COLLATE utf8_turkish_ci DEFAULT NULL,
		  `ADRES` nvarchar(400) COLLATE utf8_turkish_ci DEFAULT NULL,
`MESAI_SAAT` DECIMAL(10,2) DEFAULT NULL,
`MOLA_SAAT` DECIMAL(10,2) DEFAULT NULL,
`CUMARTESI_MESAI_SAAT` DECIMAL(10,2) DEFAULT NULL,
`CUMARTESI_MOLA_SAAT` DECIMAL(10,2) DEFAULT NULL,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_firma_ID ON t_firma (ID);
CREATE INDEX IDX_t_firma_KOD ON t_firma (KOD);

CREATE TABLE `t_firma_cihaz` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRMA_ID` int NOT NULL,
  `CIHAZ_MAKINE_GERCEK_ID` int NOT NULL, 
  `FIRMA_CIHAZ_TIP_KID` int ,
  `AD` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  `ACIKLAMA` nvarchar(500) COLLATE utf8_turkish_ci DEFAULT NULL,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_firma_cihaz_ID ON t_firma_cihaz (ID);
CREATE INDEX IDX_t_firma_cihaz_FIRMA_ID ON t_firma_cihaz (FIRMA_ID);
CREATE INDEX IDX_t_firma_cihaz_C_MAK_GER_ID ON t_firma_cihaz (CIHAZ_MAKINE_GERCEK_ID);
CREATE INDEX IDX_t_firma_cihaz_FR_CH_TP ON t_firma_cihaz (FIRMA_ID,FIRMA_CIHAZ_TIP_KID);

CREATE TABLE `t_firma_kisi` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRMA_ID` int NOT NULL,
  `KISI_ID` int NOT NULL,
  `FIRMA_KISI_TIP_KID` int ,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_firma_kisi_ID ON t_firma_kisi (ID);
CREATE INDEX IDX_t_firma_kisi_FIRMA_ID ON t_firma_kisi (FIRMA_ID);
CREATE INDEX IDX_t_firma_kisi_KISI_ID ON t_firma_kisi (KISI_ID);
CREATE INDEX IDX_t_firma_kisi_FR_KS_TP ON t_firma_kisi (KISI_ID,FIRMA_KISI_TIP_KID);

CREATE TABLE `t_hareket` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRMA_ID` int NOT NULL,
  `HAREKET_TIP_KID` int ,
  `HAREKET_DURUM_KID` int ,
  `HAREKET_KAYIT_TARIH` timestamp(6) NULL DEFAULT NULL,
  `HAREKET_DATA` nvarchar(2000) COLLATE utf8_turkish_ci DEFAULT NULL,
  `HAREKET_ISLEME_TARIH` timestamp(6) NULL DEFAULT NULL,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_hareket_ID ON t_hareket (ID);
CREATE INDEX IDX_t_hareket_FIRMA_ID ON t_hareket (FIRMA_ID);
CREATE INDEX IDX_t_hareket_FR_HR_TP ON t_hareket (FIRMA_ID,HAREKET_TIP_KID);
CREATE INDEX IDX_t_hareket_FR_HR_DR ON t_hareket (FIRMA_ID,HAREKET_DURUM_KID);
CREATE INDEX IDX_t_hareket_HAREKET_KAYIT_TARIH ON t_hareket (HAREKET_KAYIT_TARIH);

CREATE TABLE `t_pdks` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRMA_ID` int NOT NULL,
  `KISI_ID` int NOT NULL,
  `FIRMA_CIHAZ_ID` int NOT NULL,
  `GIRIS_TARIH` timestamp(6) NULL DEFAULT NULL,
  `CIKIS_TARIH` nvarchar(2000) COLLATE utf8_turkish_ci DEFAULT NULL,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_pdks_ID ON t_pdks (ID);
CREATE INDEX IDX_t_pdks_FIRMA_ID ON t_pdks (FIRMA_ID);
CREATE INDEX IDX_t_pdks_KISI_ID ON t_pdks (KISI_ID);
CREATE INDEX IDX_t_pdks_FIRMA_CIHAZ_ID ON t_pdks (FIRMA_CIHAZ_ID);
CREATE INDEX IDX_t_pdks_FR_KS ON t_pdks (FIRMA_ID,KISI_ID);
CREATE INDEX IDX_t_pdks_GIRIS_TARIH ON t_pdks (GIRIS_TARIH);
CREATE INDEX IDX_t_pdks_CIKIS_TARIH ON t_pdks (CIKIS_TARIH);

CREATE TABLE `t_pdks_hareket` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PDKS_ID` int NOT NULL,
  `HAREKET_ID` int NOT NULL,
  `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_t_pdks_hareket_ID ON t_pdks_hareket (ID);
CREATE INDEX IDX_t_pdks_hareket_PDKS_ID ON t_pdks_hareket (PDKS_ID);
CREATE INDEX IDX_t_pdks_hareket_HAREKET_ID ON t_pdks_hareket (HAREKET_ID);

----- KOD TABLOSU DOLDUR
CREATE TABLE `t_kod` (
  `ID` int NOT NULL,
  `TIP_ID` int DEFAULT NULL,
  `KOD` nvarchar(200) COLLATE utf8_turkish_ci DEFAULT NULL,
  `SIRA` int DEFAULT NULL,
  `KISA_AD` nvarchar(20) COLLATE utf8_turkish_ci DEFAULT NULL,
  `DIGER_UYG_ENUM_AD` nvarchar(50) COLLATE utf8_turkish_ci DEFAULT NULL,
  `DIGER_UYG_ID` int  NULL,
    `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_kod_ID ON t_kod (ID);

CREATE INDEX IDX_kod_TIP_ID ON t_kod (TIP_ID);

CREATE INDEX IDX_kod_DIGER_UYG_ENUM_AD ON t_kod (DIGER_UYG_ENUM_AD);

CREATE INDEX IDX_kod_DIGER_UYG_IDR ON t_kod (DIGER_UYG_ID);














CREATE TABLE `t_coin_alis` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SYMBOL` nvarchar(20) COLLATE utf8_turkish_ci DEFAULT NULL,
  `YONTEM_TIP_KOD_ID`  int(20) NOT NULL, 
  `IS_GERCEK_ISLEM` int(1) NOT NULL DEFAULT 0, 
  `TARIH_ISTEK` timestamp(6) NULL DEFAULT NULL,
  `ADET_ISTEK`DECIMAL (65,30)    NOT NULL ,
  `TOPLAM_TUTAR_ISTEK`DECIMAL (65,30)    NOT NULL ,
  `FIYAT_ISTEK`DECIMAL (65,30)    NOT NULL ,
  `ZARAR_DURDUR_FIYAT_ISTEK`DECIMAL (65,30)    NOT NULL,
  `HEDEF_FIYAT_ISTEK`DECIMAL (65,30)    NOT NULL,
  `BINANCE_TRADE_ID` int(20) NOT NULL,
  `TARIH` timestamp(6) NULL DEFAULT NULL,
  `ADET`DECIMAL (65,30)    NOT NULL ,
  `FIYAT`DECIMAL (65,30)   NOT NULL ,
  `HEDEF_FIYAT_GUNCELLEME_ORAN`DECIMAL (65,30)    NOT NULL ,
  `HEDEF_FIYAT`DECIMAL (65,30)    NOT NULL ,
  `ZARAR_DURDUR_FIYAT_GUNCELLEME_ORAN`DECIMAL (65,30)    NOT NULL ,
  `ZARAR_DURDUR_FIYAT`DECIMAL (65,30)    NOT NULL,
  `SON_GUNCELLEME_TARIH` timestamp(6) NULL DEFAULT NULL,
  `GUNCELLEME_COUNT` int NOT NULL dEFAULT 0,
  `GUNCELLEME_FEDA_BASLANGIC` int NOT NULL dEFAULT 0,
  `GUNCELLEME_FEDA_ANLIK` int NOT NULL dEFAULT 0,
  `GUNCELLEME_FEDA_ARTIS_BASAMAK` int NOT NULL dEFAULT 0,
  `GUNCELLEME_KONTROL_MIN_DEGERI` int NOT NULL dEFAULT 0,
  `TOPLAM_TUTAR`DECIMAL (65,30)    NOT NULL DEFAULT 0,
  `KOMISYON_TUTAR`DECIMAL (65,30)    NOT NULL DEFAULT 0,
  `ACIKLAMA`  nvarchar(1000) NULL,
  `KAR_ZARAR`DECIMAL (65,30)    NOT NULL DEFAULT 0,
  `ALIM_ANI_MUM_OPEN_TIME` timestamp(6) NULL DEFAULT NULL,
  `ALIM_ANI_MUM_BIRONCEKI_OPEN_TIME` timestamp(6) NULL DEFAULT NULL,
  `ALIM_ANI_MUM_TIP_DAKIKA` int NOT NULL dEFAULT 0,
   `SATIS_ISLEM_SAYISI`   int(10) NOT NULL DEFAULT 0, 
   `SATILAN_TOPLAM_ADET`  DECIMAL (65,30) NOT NULL , 
   `IS_SATISI_TAMAMLANDI` int(1) NOT NULL DEFAULT 0, 
   `MAX_PARCA_SAYISI` int(10) NOT NULL DEFAULT 0,  
   `PARCA_BASI_ADET_MIKTARI` DECIMAL (65,30)    NOT NULL ,
   `ISDELETED` int(1) NOT NULL DEFAULT 0,
  `CREATEDUSER` int(20) DEFAULT NULL,
  `CREATEDDATE` timestamp(6) NULL DEFAULT NULL,
  `MODIFIEDUSER` int(20) DEFAULT NULL,
  `MODIFIEDDATE` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

CREATE INDEX IDX_coin_alis_ID ON t_coin_alis (ID);

CREATE INDEX IDX_coin_alis_SYMBOL ON t_coin_alis (SYMBOL);

CREATE INDEX IDX_coin_alis_YONTEM_TIP_KOD_ID ON t_coin_alis (YONTEM_TIP_KOD_ID);

CREATE INDEX IDX_coin_alis_BINANCE_TRADE_ID ON t_coin_alis (BINANCE_TRADE_ID);

insert kodu
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(102,0,0,'satış sebep tip','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020001,102,1,'Manuel','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020002,102,2,'Stop Lost Çalıştı','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020003,102,3,'Satıcılar yukseldi','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020004,102,4,'Yeterlı kar a ulasıldı','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020005,102,5,'Çok fazla karsız duruldu','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020006,102,6,'Blok listesine girmis','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1020007,102,7,'izinli listesinden cıkmış','',null,null);

INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(103,0,0,'bildirim','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1030001,103,1,'Alış','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1030002,103,2,'Satış','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1030003,103,3,'Öneri','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1030004,103,4,'Genel','',null,null);

INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(104,0,0,'yöntem tip','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040001,104,1,'GENEL','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040002,104,2,'yöntem 1','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040003,104,3,'yöntem 2','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040004,104,4,'yöntem 3','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040005,104,5,'yöntem 4','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040006,104,6,'yöntem 5','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1040007,104,7,'yöntem 6','',null,null);



INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(106,0,0,'doviz alarm tip','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1060001,106,1,'altına inerse','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1060002,106,2,'üstüne çıkarsa','',null,null);

INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(107,0,0,'doviz alarm sure tip','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1070001,107,1,'tek seferlik','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1070002,107,2,'her zaman','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1070003,107,3,'gun 5','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1070004,107,4,'gun 10','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1070005,107,5,'gun 20','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1070006,107,6,'gun 30','',null,null);

INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(108,0,0,'doviz tip','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1080001,108,1,'usd','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1080002,108,2,'euro','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1080003,108,3,'altın gram','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1080004,108,4,'euro/dolar parite','',null,null);
INSERT INTO T_Kod (ID,TIP_ID,SIRA,KOD,KISA_AD,DIGER_UYG_ENUM_AD,DIGER_UYG_ID)VALUES(1080005,108,5,'sterlin','',null,null);



